server:
  port: 8088

mqtt:
  enabled: true
  bind_address: 0.0.0.0
  bind_port: 1883
  netty:
    leak_detector_level: DISABLED
    boss_group_thread_count: 1
    worker_group_thread_count: 8
    max_payload_size: 65536