server:
  port: 8088

mqtt:
  # Enable/disable mqtt transport protocol.
  enabled: true
  bind_address: 0.0.0.0
  bind_port: 1883
  timeout: 10000
  netty:
    leak_detector_level: DISABLED
    boss_group_thread_count: 1
    worker_group_thread_count: 8
    max_payload_size: 65536
    so_keep_alive: false
  # MQTT SSL configuration
  ssl:
    # Enable/disable SSL support
    enabled: false
    # MQTT SSL bind address
    bind_address: 0.0.0.0
    # MQTT SSL bind port
    bind_port: 8883
    # SSL protocol: See https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html#sslcontext-algorithms
    protocol: TLSv1.2
    # Server SSL credentials
    credentials:
      # Server credentials type (PEM - pem certificate file; KEYSTORE - java keystore)
      type: PEM
      # PEM server credentials
      pem:
        # Path to the server certificate file (holds server certificate or certificate chain, may include server private key)
        cert_file: mqttsrver.pem
        # Path to the server certificate private key file. Optional by default. Required if the private key is not present in server certificate file;
        key_file: mqttserver_key.pem
        # Server certificate private key password (optional)
        key_password: server_key_password
      # Keystore server credentials
      keystore:
        # Type of the key store (JKS or PKCS12)
        type: JKS
        # Path to the key store that holds the SSL certificate
        store_file: mqttserver.jks
        # Password used to access the key store
        store_password: server_ks_password
        # Optional alias of the private key; If not set, the platform will load the first private key from the keystore;
        key_alias:
        # Optional password to access the private key, If not set, the platform will attempt to load the private keys that are not protected with the password;
        key_password: server_key_password


spring:
  application:
    name: IoT-Technology-MQTT-Broker
  redis:
    redisson:
      file: classpath:redisson.yml